set timeout 120
set prompt "# $"
log_file -noappend "~/exos-console.explog"

spawn telnet 127.0.0.1 52099

# marker to log in
expect "master node is now available for login"
sleep 10
send "\r"

# log in with default 'admin' account
expect "login:"
send "admin\r"
expect "password:"
send "\r"

# bypass safe defaults mode
expect "disable MSTP"
send "quit\r"
expect $prompt

# lab feature(s)
send "disable cli idle-timeout\r"
expect $prompt

# create the vagrant user 
send "create account admin vagrant vagrant\r"
expect $prompt

# configure ssh
send "create sshd2 user-key vagrant AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==\r"
expect $prompt
send "configure sshd2 user-key vagrant add user vagrant\r"
expect $prompt
send "enable ssh2 vr VR-Mgmt\r"
expect "Continue"
send "Yes\r"
expect "Key Generated"

# configure the management interface
send "enable dhcp vlan Mgmt\r"
expect $prompt

# save the configuration to nvram
send "save\r"
expect "save configuration to primary.cfg"
send "Yes\r"
expect $prompt

# allow time for save to happen
sleep 10
send "\r"
expect $prompt
